### PR TITLE
Fix unnamed import symbols

### LINKED ISSUE #125: Imported contract symbols not resolving properly
### Problem

There seems to be some sort of issue resolving imported symbols.  This appeared in https://github.com/onflow/vscode-cadence/issues/312 when we updated vscode-langaugeclient from 8.0.2 to 8.1.0 - we have since downgraded to prevent this error message.

I think what happened was not that this actually created any new issue, but rather that vscode just was not displaying the error prior (see https://github.com/microsoft/vscode-languageserver-node/commit/55eb8e349c58d276ed672064b81b5c4d271e0d16).  I say this because if you install the VSCode Cadence extension right now and type in the name of an imported contract and start typing one of its children (i.e. `FlowToken.Vau`) you will not see any sort of autocomplete suggestion (i.e. `FlowToken.Vault`).

I did some logging in order to debug this.  Below is the output of the `textDocument/documentSymbol` response for the FlowToken contract.

Screen Shot 2023-05-24 at 4 40 54 PM

Below now is the output of the `textDocument/documentSymbol` response for the FungibleToken contract.

Screen Shot 2023-05-24 at 4 42 49 PM

Notice how the contract defined in the file itself resolves fine (all the children exist and everything) but imported contracts are not properly resolved.  They are simply empty with no children and no name (the error we see is because of the empty name which is invalid).

### Steps to Reproduce 

Try to update vscode-languageclient in vscode-cadence and use the extension on a file with one or more imports.  It will begin to throw the error.

### PR DESCRIPTION
**Pull request by jribbink**
Closes #125 

## Description

This PR solves import symbols having no name in LSP responses and causing errors in the client/vscode extension.

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence-lint/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by turbolent — APPROVED** [review]
Nice, thank you!

File: languageserver/conversion/conversion.go [hunk 1]
```diff
@@ -127,6 +127,8 @@ func DeclarationToDocumentSymbol(declaration ast.Declaration) protocol.DocumentS
 			name = "init"
 		case common.DeclarationKindDestructor:
 			name = "destroy"
+		case common.DeclarationKindImport:
```
Comment (turbolent) [inline languageserver/conversion/conversion.go:130]: That should fix the case when the program has an import declaration 👍 

I had a quick look and there are some more cases where the declaration does not have an identifier (`DeclarationIdentifier()` returns `nil`), e.g. pragmas.

Instead of handling specific cases in the fallback (when there is no identifier available), maybe we can instead handle this in general by using the `DeclarationKind.Keywords()`, it pretty much returns what we would like to see as a document symbol name. 

Could you please replace the whole switch case with just this (GitHub does not let me provide a suggestion for non-edited code):
```go
name = declarationKind.Keywords()
```

**Review by turbolent — COMMENTED** [review]
Nice, thank you for fixing this!

File: languageserver/conversion/conversion.go (hunk 1 above)
Comment (jribbink) [reply languageserver/conversion/conversion.go]: nice!  didn't know this existed.  threw that in there as well as a filter that all symbols must have a non-empty name just in case declaration.Keywords() is missing symbols in the future.

**Review by SupunS — APPROVED** [review]

File: languageserver/conversion/conversion.go (hunk 1 above)
Comment (turbolent) [reply languageserver/conversion/conversion.go]: Perfect, thanks!

**Review by turbolent — APPROVED** [review]
Thank you!
