### PR TITLE
[LS] Allow importing any flow.json contracts using new import syntax

### LINKED ISSUE #222: [LS] String import resolution does not work with aliases
### Current Behavior

Currently, string imports are resolved only from the `deployments` section of `flow.json`, however, are not resolved from aliased cotrats.  This means that when checking contracts, particularly with pre-deployed/core contracts, imports may not resolve properly.

(see `integration/flow.go`)
Screenshot 2023-10-19 at 2 12 24 PM

### Expected Behavior

The LS should recognize contracts deployed contracts outside of the `deployments` section as well (aliases).  This probably means simply resolving anything from the `contracts` section of `flow.json` regardless of whether they appear in `deployments` or not.

### Steps To Reproduce

Try to use this project in VSCode with Cadence extension.

contracts/foo/Foo.cdc
```cadence
import "NonFungibleToken"

pub contract Foo {}
```

flow.json
```json
{
	"contracts": {
		"Foo": "cadence/contracts/foo/Foo.cdc",
		"NonFungibleToken": {
			"source": "cadence/contracts/standard/NonFungibleToken.cdc",
			"aliases": {
				"emulator": "f8d6e0586b0a20c7"
			}
		}
	},
	"networks": {
		"emulator": "127.0.0.1:3569",
		"mainnet": "access.mainnet.nodes.onflow.org:9000",
		"sandboxnet": "access.sandboxnet.nodes.onflow.org:9000",
		"testnet": "access.devnet.nodes.onflow.org:9000"
	},
	"accounts": {
		"default": {
			"address": "ff8975b2fe6fb6f1",
			"key": "4656ee827102b8b4f5c34b4b29afad3d75f61284f52e9b9573cade37b1b7bda4"
		},
		"emulator-account": {
			"address": "f8d6e0586b0a20c7",
			"key": "4656ee827102b8b4f5c34b4b29afad3d75f61284f52e9b9573cade37b1b7bda4"
		},
		"foo": {
			"address": "e9dd1081676bbc90",
			"key": "4656ee827102b8b4f5c34b4b29afad3d75f61284f52e9b9573cade37b1b7bda4"
		},
		"standard": {
			"address": "0dbaa95c7691bc4f",
			"key": "4656ee827102b8b4f5c34b4b29afad3d75f61284f52e9b9573cade37b1b7bda4"
		}
	},
	"deployments": {
		"emulator": {
			"default": [],
			"foo": [
				"Foo"
			],
			"standard": []
		}
	}
}
```

You will see this error

Screenshot 2023-10-19 at 3 04 39 PM

### Environment

```markdown
- LS Version: v0.32.0
- Network: Emulator
```

### PR DESCRIPTION
**Pull request by jribbink**
Closes #222 

## Description

Previously, when using new import syntax, only contracts referenced in `deployments` section of `flow.json` for the emulator network were resolved.  This did not account for aliased contracts & if the dev chose not to configure emulator deployments for whatever reason.

This PR changes to behaviour to simply resolve any contract in the `contracts` section of `flow.json` from the corresponding source location.

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence-lint/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by turbolent — COMMENTED** [review]
Nice, thank you!

**Comment by turbolent** [comment]
Please follow and complete the checklist, e.g. add a label to the PR

File: languageserver/integration/flow.go [hunk 1]
```diff
@@ -393,23 +393,37 @@ func (f *flowkitClient) createSigner(address flow.Address) (*accounts.Account, e
...
+	}
+	return code, nil
 }
 
 // Helpers
 //
 
+// Helper function to get code from a source file location
+func (f *flowkitClient) getCodeFromLocation(name, location string) (string, error) {
+	code, err := f.loader.ReadFile(filepath.Join(filepath.Dir(f.getConfigPath()), location))
```
Comment (SupunS) [inline languageserver/integration/flow.go:420]: Just for improved readability:
```suggestion
	dir := filepath.Dir(f.getConfigPath())
	path := filepath.Join(dir, location)
	code, err := f.loader.ReadFile(path)
```

**Review by SupunS — APPROVED** [review]
